---
title: "Stat230: Applied Regression Analysis"
subtitle: "Fall 2026"
navbar: false
execute:
  freeze: true
typst-logo:
  path: "logo.png"
format: 
  html: default
  syllabus-typst: default
editor: 
  markdown: 
    wrap: 72
---

::: {.boxed-text}

+------------+-------------------------------------------+---------+
| MEETINGS:  | MWF 4a                                    | CMC 306 |
|            |                                           |         |
|            | 12:30-1:40 MW; 1:10-2:10 F                |         |
+------------+-------------------------------------------+---------+
| PROFESSOR: | Amanda Luby                               | CMC 223 |
|            | aluby@carleton                            |         |
+------------+-------------------------------------------+---------+
| DROP-IN:   |                                           | CMC 307 |
|            | Mon 3-4pm                                 |         |
|            |                                           |         |
|            | Tues 10:30-11:30am                        |         |
|            |                                           |         |
|            | Wed 2-3pm (220 priority)                  |         |
|            |                                           |         |
|            | Fri 11:30-12:30 (230 priority)            |         |
|            |                                           |         |
|            | Or by appointment!                        |         |
+------------+-------------------------------------------+---------+
| WEBSITE:   | moodle.carleton.edu                       |         |
+------------+-------------------------------------------+---------+
| TEXT:      | Readings primarily assigned from          |         |
|            |Introduction to Regression Analysis by     |         |
|            | M. Tackett                                |         |
|            | [Freely available online](https://introregression.netlify.app/00-preface)      |         |
+------------+-------------------------------------------+---------+
| SOFTWARE:  |                                           |         |
|            |  maize.mathcs.carleton.edu  (R code)      |         |
|            |                                           |         |
|            |  gradescope  (homework)                   |         |
+------------+-------------------------------------------+---------+

: {tbl-colwidths="[30,50,20]"}

:::

```{=typst}
#colbreak()
```

# Course Description

Our world is awash in data. To make decisions based on evidence, we must
be able to make sense of the data around us and communicate our
findings. In this course, we will explore how to incorporate multiple
predictors into regression models to answer complex questions. In
addition to modeling continuous response variables, we will also explore
models for binary data, and binomial and Poisson counts. This course
will emphasize model building, model validation, and how to communicate
results. We will make frequent use of R.

# Course Objectives

After completing this course, you should be able to demonstrate your
competency in each of the following areas:

  - Develop research questions that can be answered using a regression model 
  - Fit linear, logistic, and Poisson regression models in R and interpret the output. 
  - Conduct inference for the model parameters and/or predictions and interpret the results in context. 
  - Comment on the adequacy of a model for addressing
  a given question of interest by assessing the assumptions underlying the
  model. 
  - Apply appropriate transformations to improve agreement with the
  model assumptions. 
  - Use statistical reasoning to select the most
  adequate for the question at hand. 
  - Communicate the results of a
  regression analysis effectively in written format.

# What I expect from you

-   **Come prepared to learn**. Complete background readings and bring
    your notes, assignments, and laptop with you to class. Be ready to
    engage in discussion and activities from the first minute of class.
-   **Do your own work**. Always give credit when using others' ideas,
    code, and writing. Review the collaboration policy for each
    assignment and follow it.
-   **Show up and join in**. This is a hands-on class where we will
    learn by doing.
-   **Be a good teammate**. Pull your weight, respect deadlines, ask
    questions when you're confused, and contribute your perspective.
-   **Use technology wisely**. Laptops and phones are great tools, but
    easy distractions. Recognize when they are helping and when they are
    hurting your learning.
-   **Manage your time and workload**. You will have lots to do during
    this course. I offer options for flexibility, but you will need to
    balance this flexibility throughout the term.

# What you can expect from me

-   **Be accessible**. I will hold four drop-in hours per week and am
    glad to set up individual appointments as needed.
-   **Timely responses**. I will respond to Ed messages within 24 hours
    and emails within 48 hours on weekdays (and as soon as I can on
    weekends).
-   **Prompt feedback**. I will return graded assignments to you within
    one week
-   **Seek your feedback**. I will ask for your feedback at least twice
    during the term, and I welcome your thoughts at any time. I value
    candid and constructive comments to help me improve as a teacher
-   **Support equitable access**. I will work with you and the Office of
    Accessibility Resources (OAR) to make sure accommodations are in
    place so everyone can fully participate in this course.
-   **Care about your well-being**. I recognize that life outside the
    classroom can be stressful. I will do my best to be flexible and
    supportive, and to connect you with resources when you need them.

# Course Components

## Meetings

There will be three course meetings per week (Mondays, Wednesdays, and
Fridays). Daily attendance is expected. Course meetings will combine
demonstrations using R, theoretical background, and in-class group
exercises. Please show up ready to participate and engage from the first minute of class! 

## Homework Assignments

Homework will be assigned once per week (typically due
Fridays) and should be submitted on gradescope before class. There is an
8 hour grace period for each assignment. If you are ill or have an
emergency, please contact me to arrange an alternative due date.
For most assignments, I expect you to use a quarto document to include your code, results, and conclusions. Any handwritten work must be neatly written and incorporated into a PDF submission. You must show all work to receive credit.

## Case Studies

There will be two case studies throughout the term. These will
ask you to analyze a dataset using tools from the course and clearly
report your findings in writing. These are larger and more open-ended
than a typical homework assignment and are preparation for your final
project. You'll work in pairs or small groups (which I will form with
your input).

## Quizzes

A key part of statistical literacy is being able to recall concepts “on
the fly”. I use in-class quizzes to assess your understanding of class
material without access to resources. There will be three quizzes
— tentatively scheduled for **Week 3 Monday, 6 Wednesday, and 9
Monday**.

If you miss a quiz due to a conflict with less than 1 week notice,
then there are no revisions or makeups offered. If must miss an exam due
to an illness or other last minute emergency, please let me know in
advance to arrange an alternative.

## Final Project

The final project is your capstone experience for the course. It's
designed to tie everything together that you've learned: you will find a
dataset, develop research questions, construct a model, and report your
findings. You'll work in pairs or small groups (which I will form with
your input). More details and grading criteria will be provided later in
the term.

## Communication

Assignments, materials for course meetings, and grades will be posted on Moodle. We will
also use Ed for announcements, discussion, and homework questions.
Please use Ed for any homework or course content questions; email me
privately with any personal matters (grade discussions, illness,
emergency, etc.). Any time-sensitive announcements will be posted on Ed.
It is your responsibility to make sure that your notification settings
allow time-sensitive announcements to reach you.

# Grading Policies

Grades are an imperfect measure of learning, and no grading scheme will
perfectly capture your "true" learning in this course. This grading
scheme is designed to reward you for consistently participating, staying
on top of the course material, and demonstrating proficiency with the
content through in-class assessments.

Final grades will be calculated as follows:

-   10% Homework
-   40% Quizzes (equally weighted)
-   25% Final Project
-   20% Case Studies (10% each)
-   5% Engagement and Professionalism

Letter grades will be assigned based on the usual grading scale (A = 93%
and above, A- = 90-92.9%, B+ = 88-89.9%, B = 83-87.9%, etc.).

*A note on the "genius myth"*: I’ve found that many carls buy into the
“genius myth” when it comes to math/stat courses: that you need to be a
“math person” and have some innate mathematical ability in order to do
well. This could not be further from the truth! The best statisticians
don’t necessarily have the “best” math or programming background, but
are people that are able to formulate interesting questions and use math
and programming to answer those questions. Many of the best
statisticians I know became statisticians because they were initially
interested in something else (biology, public health, psychology,
neuroscience, physics, etc.) and realized that being able to answer
important questions with data was not only valuable but fun and
interesting. Being able to perform interesting statistical analyses is a
skill that is learned, not an innate ability, and working hard at
developing that skill is the point of this course.

## Engagement and Professionalism

In this course, you will be working with teammates on formal assessments (case studies, the final project) as well as informal in-class work. Your contributions to each case study or project will be incorporated into those grades. Your engagement and professionalism grade will be determined holistically based on attendance, group evaluation surveys, and my observations during class. 

- A level: Shows up to class prepared almost every day. Is a good communicator, walks teammates through thought processes carefully, asks questions of teammates and Amanda when confused. Technology use is almost always on task.
- B level: Shows up to class prepared most days. Participates in group work and follows along with teammates' reasoning, but is less proactive about explaining their own thinking or flagging confusion in the moment. Technology use is sometimes off-task during group work.
- C level: Shows up to class prepared inconsistently. Participates when directed to, but rarely initiates discussion, checks that teammates understand, or asks for help when stuck. Technology use is often off-task during group work.
- D/F level: Rarely shows up to class prepared. Doesn't participate when prompted. 

All levels above are premised on attendance almost every day, and missing more than 1-2 days of class will heavily impact your P&E grade. More than 5 absences will result in a 0%, other than in exceptional circumstances. Please speak with me if you will be away from campus for an extended period or have an emergency arise.

## Regrade requests

Grading is often a tedious task, and the grading team will sometimes
make mistakes. I am always happy to fix these mistakes, and gradescope
makes it easy to do so. Regrade requests must be submitted on gradescope
within two weekdays after an assignment or exam has been returned to
you. Regrade requests are for administrative errors or obvious grading
mistakes. I will not consider regrade requests for anything that applied
to the entire class (e.g. “I think this mistake should only be worth 1
point instead of 2” or “I didn’t realize we had to do X”). If you submit
two or more inappropriate regrade requests, I will not consider
additional regrade requests from you for the remainder of the term. If
you’re unsure whether you should file a regrade request or not, just
ask! You are **always** welcome to discuss any grading questions with me in
office hours.

## Tokens

You have 3 tokens to use throughout the term. Tokens can be used for:

-   a 48-hour extension on homework (individual) or case study (all team members must use a token) due date
-   revise a case study (individual)
-   retake a quiz

## Quiz retakes

I offer the opportunity to retake a quiz for two reasons: (1)
to correct any major misunderstandings and have a chance to revisit
material that you struggled with, (2) to mitigate the impact that a bad
exam day can have on your final course grade. 
You can complete a short retake quiz to earn back 25% of the points that you missed. 
The retake quiz questions will cover the same topics but use new numbers/context. 
Quiz retakes must be completed before the next quiz, or the last day of class at 11:59pm, whichever is earlier.

## Case Study revisions

Revised case studies are due 1 week after graded case studies are
returned to you, or the last day of class at 11:59pm, whichever is
earlier.

# Academic Integrity

You are expected to follow Carleton’s [policies regarding academic
integrity](https://www.carleton.edu/handbook/academics/?policy=329). I
encourage you to discuss the homework problems with other humans and do
background reading as needed. You should code and write up your
solutions on your own. Quizzes must be done by yourself without
communicating with others; all work must be your own. You should
collaborate with your teammates on projects, and should use external
resources for background research and debugging, but all work should be
original and all sources should be properly cited. The use of textbook
solution manuals (physical or online), course materials from other
students, or materials from previous versions of this course are not
allowed.

Large-language models (e.g. ChatGPT, Claude, Gemini, etc.) should only be used
for coding or debugging help after you’ve attempted to solve the problem
on your own, and you should never type homework problems directly into a
prompt. Copying, paraphrasing, summarizing, or submitting work generated
by anyone but yourself without proper attribution is considered academic
dishonesty (this includes output from LLMs).

I also have a few rules in place to protect my intellectual property.
You may not record my lectures using tools such as Otter.ai or upload
any video or audio recordings to generate transcripts or study notes.
You may not upload my course materials (slides, assignment prompts, note
sets, etc.) into AI tools or homework help sites.

“AI” tools are new for all of us and it’s OK to have questions about
what is and isn’t appropriate. Please ask if you are unsure of whether
or not your actions are complying with the assignment/quiz/project
instructions. Always default to acknowledging any help received. Cases
of suspected academic dishonesty are handled by the Provost’s Office and
I am obligated to report any suspected violations of this policy.

# Diversity and Inclusion

We all come to class with different backgrounds and experiences, and
this diversity makes our class environment richer. I value diversity and
inclusion, and am committed to a climate of mutual respect and full
participation in and out of the classroom. This class strives to be a
learning environment that is usable, equitable, inclusive and welcoming,
regardless of race, ethnicity, religion, gender and gender identities,
sexual orientation, ability, socioeconomic background, and nationality.
If you anticipate or experience any barriers to learning, please discuss
your concerns with me.

# Resources

## Professor availability

Please reach out to me if you have any questions! You can reach me on
Ed, email, drop-in hours, or make an appointment. Ed is typically the
best venue for homework/content questions outside of drop-in hours. I’ll
respond to Ed messages at least twice each week day, and try to
respond to emails within 48 hours. You will receive responses faster on
Ed than email. I am online irregularly over evenings and weekends to
devote time to family and rest, and I hope that you also find time to recharge and reset!

## Accomodations

Carleton College is committed to providing equitable access to learning
opportunities for all students. The Office of Accessibility Resources
(Henry House, 107 Union Street) is the campus office that collaborates
with students who have disabilities to provide and/or arrange reasonable
accommodations. If you have, or think you may have, a disability, please
contact OAR\@carleton.edu to arrange a confidential discussion regarding
equitable access and reasonable accommodations. You are also welcome to
contact me privately to discuss your academic needs. However, all
disability-related accommodations must be arranged, in advance, through
OAR.

## Stat Lab

The Stats Lab (CMC 331) offers drop-in help R/RStudio help sessions run
by friendly and knowledgeable lab assistants from 7-10pm Sunday through
Thursday evenings. To make the most of your time, attempt homework
problems on your own beforehand and bring your class notes and lab
manual as these are helpful references for both you and the lab
assistant.

## Title IX

Please be aware that all faculty are “responsible employees”, which
means that if you tell me about a situation involving sexual harassment,
sexual assault, dating violence, domestic violence, or stalking, I must
share that information with the Title IX Coordinator. Although I have to
make this notification, you will control how your case will be handled,
including whether or not you wish to meet with the Title IX coordinator
or pursue a formal complaint.

## Take care of yourself

Do your best to maintain a healthy lifestyle this term by wearing a mask
when you’re sick, eating a vegetable every now and then, exercising,
avoiding excessive drug and alcohol use, getting enough sleep, and
taking some time to relax. Your physical and mental health is more
important than your grade in this course. There are many helpful
resources available on campus and an important part of the college
experience is learning how to ask for help. For more information, see
Student Health and Counseling (SHAC), the Office of Health Promotion, or
the Office of the Chaplain. If you are experiencing physical or mental
health symptoms as a result of coursework, please speak with me so we
can address the problem together.
