<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Example prepared by Dr.&nbsp;Luby — Stat230">

<title>Bigger Bodies, Bigger Brains? – stat230</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f4f5b63388da9725c4ce2c62b8120838.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.scss">
</head>

<body class="quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis-and-a-first-model" id="toc-exploratory-data-analysis-and-a-first-model" class="nav-link" data-scroll-target="#exploratory-data-analysis-and-a-first-model">Exploratory data analysis and a first model</a></li>
  <li><a href="#transforming-the-data" id="toc-transforming-the-data" class="nav-link" data-scroll-target="#transforming-the-data">Transforming the data</a></li>
  <li><a href="#interpretation-and-conclusions" id="toc-interpretation-and-conclusions" class="nav-link" data-scroll-target="#interpretation-and-conclusions">Interpretation and conclusions</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bigger Bodies, Bigger Brains?</h1>
<p class="subtitle lead">Modeling the relationship between mammal body weight and brain weight</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Example prepared by Dr.&nbsp;Luby — Stat230 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Before you read this
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is an <strong>annotated example</strong>, not a template to copy sentence-for-sentence. It uses the mammal brain/body weight data from Activity 06 and follows the same three phases as the Case Study 1 prompt (EDA + first model, transform, interpret). The notes in the margins point out <em>why</em> each part works, usually by tying it back to a specific line on the rubric.</p>
<p>Two things are deliberately different from what your real submission should look like:</p>
<ol type="1">
<li><strong>Code visibility.</strong> I’ve left <code>echo: true</code> on here so you can see the R code and the write-up side by side while you’re learning. Your actual Results section should read like a polished narrative with the code hidden (<code>echo: false</code>) — the rubric wants a separate Quarto appendix file with the code, not code embedded in the report itself.</li>
<li><strong>Length.</strong> With the margin notes included this renders longer than 3 pages. Imagine the notes aren’t there — the report text itself is close to the page limit you’ll be working with.</li>
</ol>
</div>
</div>
<section id="introduction" class="level1 page-columns page-full">
<h1>Introduction</h1>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> the first two sentences motivate the question before any data appears, and the claim about metabolic cost is backed by a citation rather than asserted as common knowledge. That’s the “avoids broad, unsubstantiated claims” rubric line in action.</p>
</div></div><p>Why do some animals have proportionally larger brains than others? Brain tissue is metabolically expensive to build and maintain, so biologists have long been interested in whether brain size simply tracks body size across species, or whether some groups of mammals have evolved brains that are disproportionately large (or small) relative to their body size (Jerison, 1973) [<em>placeholder citation — swap in a source you’ve actually read for your own report</em>]. If brain weight scaled in exact proportion to body weight, we’d expect a 10-kg animal to have roughly ten times the brain mass of a 1-kg animal. Whether that’s true, and by how much real mammals deviate from it, is a natural question to explore with a simple linear regression.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> this paragraph states the actual research question in plain language before any statistics appear, which is what the rubric means by “explains the questions addressed in the report.”</p>
</div></div><p>In this report, we model the relationship between <strong>body weight</strong> (in kilograms) and <strong>brain weight</strong> (in grams) using a sample of 30 mammal species, originally compiled by Allison and Cicchetti (1976) for a study of sleep patterns across mammals. Our goal is to describe how brain weight changes as body weight increases, and to see whether that relationship is proportional (doubling body weight doubles brain weight) or not.</p>
</section>
<section id="results" class="level1 page-columns page-full">
<h1>Results</h1>
<section id="exploratory-data-analysis-and-a-first-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-and-a-first-model">Exploratory data analysis and a first model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggResidpanel)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>weight <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/weights.csv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">species =</span> <span class="fu">str_squish</span>(species)) <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(bodyweight, brainweight)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(weight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           species bodyweight brainweight maximumlifespan gestationtime
1 African elephant   6654.000      5712.0            38.6           645
2       Arctic Fox      3.385        44.5            14.0            60
3   Asian elephant   2547.000      4603.0            69.0           624
4           Baboon     10.550       179.5            27.0           180
5    Big brown bat      0.023         0.3            19.0            35
6              Cat      3.300        25.6            28.0            63
  totalsleep
1        3.3
2       12.5
3        3.9
4        9.8
5       19.7
6       14.5</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> <code>str_squish()</code> isn’t needed for the two variables we end up using, but a quick look at the raw file (<code>View(weight)</code>) showed inconsistent trailing whitespace in the species names. Cleaning it up costs one line and is good practice even when it doesn’t change your numbers — it’s the kind of small check a careful analyst does automatically.</p>
</div></div><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">gf_point</span>(brainweight <span class="sc">~</span> bodyweight, <span class="at">data =</span> weight) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Body weight (kg)"</span>, <span class="at">y =</span> <span class="st">"Brain weight (g)"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Brain weight vs. body weight"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">gf_histogram</span>(<span class="sc">~</span> bodyweight, <span class="at">data =</span> weight) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title =</span> <span class="st">"Distribution of body weight"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">gf_histogram</span>(<span class="sc">~</span> brainweight, <span class="at">data =</span> weight) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">title =</span> <span class="st">"Distribution of brain weight"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> (p2 <span class="sc">/</span> p3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mammal-brain-weights-example_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> three plots, one sentence of description each, no restating of what’s visually obvious. The write-up says <em>what it means</em>, not just <em>what it shows</em>.</p>
</div></div><p>The scatterplot shows a clear positive association: species with larger bodies tend to have larger brains. But both marginal distributions are <strong>strongly right-skewed</strong> — most of our 30 species weigh well under 100 kg, with two elephants sitting far out on their own above 2,500 kg. A handful of extreme points sitting alone like this is exactly the situation where a linear model can be misleading, so we fit one anyway, as a baseline to compare against.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>weight_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(brainweight <span class="sc">~</span> bodyweight, <span class="at">data =</span> weight)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weight_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = brainweight ~ bodyweight, data = weight)

Residuals:
    Min      1Q  Median      3Q     Max 
-766.62 -169.87 -127.10    0.85 2017.62 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 170.94214   90.95932   1.879   0.0706 .  
bodyweight    0.94795    0.06931  13.678  6.4e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 475.5 on 28 degrees of freedom
Multiple R-squared:  0.8698,    Adjusted R-squared:  0.8652 
F-statistic: 187.1 on 1 and 28 DF,  p-value: 6.403e-14</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(weight_lm, <span class="at">plots =</span> <span class="fu">c</span>(<span class="st">"resid"</span>, <span class="st">"index"</span>, <span class="st">"qq"</span>), <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mammal-brain-weights-example_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> each sentence below names a <em>specific</em> SLR condition (linearity, equal variance, normality) and points to the <em>specific</em> plot feature that supports the claim. Compare that to a vague “the conditions don’t look great” — the rubric calls this “technical language used correctly.”</p>
</div></div><p>The fitted model is reported in the output above. Although the slope is highly statistically significant (<span class="math inline">\(t = 13.68\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and <span class="math inline">\(R^2 = 0.870\)</span> looks encouraging, we don’t trust this model yet. Two things stand out in the diagnostics:</p>
<ul>
<li><strong>Equal variance is badly violated.</strong> The residual-vs-fitted plot fans out dramatically — residuals near zero are tightly packed, while the two elephants produce residuals in the thousands. In fact, the African elephant alone has a leverage value of 0.87, meaning that one observation is doing almost as much work in determining the regression line as the other 29 combined.</li>
<li><strong>Normality is badly violated.</strong> The normal probability plot curves sharply away from the reference line at both ends, driven by the same handful of large-bodied, large-residual species (Asian elephant, Man).</li>
</ul>
<p>Both problems trace back to the same root cause we saw in the EDA: extreme right skew in both variables. A transformation is the natural next step.</p>
</section>
<section id="transforming-the-data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="transforming-the-data">Transforming the data</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> the choice of transformation is <em>justified from the EDA</em>, not just tried because the activity suggested it. “Both variables are right-skewed across several orders of magnitude” is a specific, defensible reason to reach for logs rather than, say, a square root.</p>
</div></div><p>Because both body weight and brain weight are right-skewed and span several orders of magnitude (from a 10-gram bat to a 6,654-kg elephant), a <strong>log-log transformation</strong> is a natural choice — it compresses large values much more than small ones, pulling the extreme points back toward the bulk of the data on both axes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>weight_log_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(brainweight) <span class="sc">~</span> <span class="fu">log</span>(bodyweight), <span class="at">data =</span> weight)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weight_log_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(brainweight) ~ log(bodyweight), data = weight)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7808 -0.5007 -0.1305  0.3515  1.8607 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      2.19038    0.17610   12.44 6.36e-13 ***
log(bodyweight)  0.75943    0.04181   18.16  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7864 on 28 degrees of freedom
Multiple R-squared:  0.9218,    Adjusted R-squared:  0.919 
F-statistic: 329.9 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(weight_log_lm, <span class="at">plots =</span> <span class="fu">c</span>(<span class="st">"resid"</span>, <span class="st">"index"</span>, <span class="st">"qq"</span>), <span class="at">nrow =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mammal-brain-weights-example_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> “reasonably met” is the actual bar, not “perfect.” This paragraph says so explicitly and still names the two points that remain unusual, instead of pretending the model is flawless.</p>
</div></div><p>The transformed model is a clear improvement. The residual-vs-fitted plot no longer fans out — spread is roughly constant across the range of fitted values — and the normal probability plot hugs the reference line much more closely, with only mild deviation at the extremes. Leverage is also far more evenly distributed across species (the highest leverage point, the little brown bat, now has leverage of 0.17, compared to 0.87 before). The SLR conditions are reasonably met for this model. Two residuals are still worth a second look — Man, whose brain weight is about 6.4 times what the model predicts, and the water opossum, whose brain weight is only about 17% of what the model predicts — but we’ll return to those in the Discussion rather than treat them as reasons to distrust the model.</p>
</section>
<section id="interpretation-and-conclusions" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="interpretation-and-conclusions">Interpretation and conclusions</h2>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> the equation is given in <em>both</em> forms — the one that was actually fit (log-log) and the back-transformed version on the original scale — because the rubric asks for “the equation” and a reader shouldn’t have to do the algebra themselves.</p>
</div></div><p>On the transformed scale, the fitted model is</p>
<p><span class="math display">\[\widehat{\log(\text{brainweight})} = 2.190 + 0.759 \cdot \log(\text{bodyweight})\]</span></p>
<p>Back-transforming to the original scale (grams and kilograms) gives</p>
<p><span class="math display">\[\widehat{\text{brainweight}} = e^{2.190} \cdot \text{bodyweight}^{0.759} = 8.94 \cdot \text{bodyweight}^{0.759}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(brainweight <span class="sc">~</span> bodyweight, <span class="at">data =</span> weight) <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lm</span>(<span class="at">formula =</span> <span class="fu">log</span>(y) <span class="sc">~</span> <span class="fu">log</span>(x), <span class="at">backtrans =</span> exp, <span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">x =</span> <span class="st">"Body weight (kg)"</span>, <span class="at">y =</span> <span class="st">"Brain weight (g)"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Back-transformed model on the original scale"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mammal-brain-weights-example_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> this is the step most reports lose points on. The interpretation doesn’t say “a one-unit increase in log(bodyweight)” — nobody thinks in log-kilograms. It translates the slope back into a statement about the original units, which is what “your interpretation must involve back-transforming” means in practice.</p>
</div></div><p><strong>Interpreting the slope.</strong> Because both variables are logged, the slope of 0.759 has a <em>percentage</em> interpretation: for every 1% increase in a species’ body weight, we expect its brain weight to increase by about 0.759%, on average. A 95% confidence interval for the true slope is (0.674, 0.845) — notably, this entire interval is below 1, giving strong evidence that brain weight scales <strong>sub-proportionally</strong> with body weight across mammals. In concrete terms, when body weight doubles, predicted brain weight is multiplied by <span class="math inline">\(2^{0.759} \approx 1.69\)</span> — a 69% increase, not a 100% increase. Bigger-bodied mammals tend to have relatively <em>smaller</em> brains for their size, not larger ones.</p>
<p><strong>Interpreting the intercept.</strong> The back-transformed intercept, <span class="math inline">\(e^{2.190} \approx 8.94\)</span> grams, is the model’s predicted brain weight for a 1-kg mammal (since <span class="math inline">\(\log(1) = 0\)</span>). A 95% confidence interval for the slope on the log scale was given above; for the intercept it is (1.830, 2.551) on the log scale, or roughly (6.2 g, 12.8 g) back-transformed. Unlike many regression examples, this intercept is <strong>not</strong> an extrapolation — our smallest species (a 10-gram bat) and largest (a 6,654-kg elephant) comfortably bracket a 1-kg animal, so this is a legitimate, interpretable prediction rather than a nonsensical one.</p>
<p><strong>Overall conclusion.</strong> Body weight is a strong predictor of brain weight across mammal species: the log-log model explains about 92% of the variability in log brain weight (<span class="math inline">\(R^2 = 0.922\)</span>), compared to 87% for the untransformed model, and does so while actually satisfying the SLR conditions. The relationship follows a power law with exponent well below 1, meaning mammalian brains do not scale in direct proportion to body size — larger animals get relatively less brain per kilogram of body, not more.</p>
</section>
</section>
<section id="discussion" class="level1 page-columns page-full">
<h1>Discussion</h1>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> no new numbers appear in this section — everything here was already established in Results. That’s what “no new results should appear here” means: Discussion <em>synthesizes</em>, it doesn’t <em>analyze</em>.</p>
</div></div><p>Across 30 mammal species, body weight and brain weight are strongly associated, but not in direct proportion: our model estimates that brain weight grows at roughly the 0.76 power of body weight, so larger mammals carry relatively less brain mass per kilogram than smaller ones. This is consistent with the idea that brain tissue is metabolically costly, and that body size and brain size are shaped by somewhat different evolutionary pressures.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> limitations here are <em>specific to this dataset and this model</em>, not a generic disclaimer like “our sample size was small.” Compare “species-level averages hide within-species variation” to a vague “there could be errors in the data.”</p>
</div></div><p>A few limitations are worth noting. First, this is a cross-species regression on <strong>species-level averages</strong>, not individual animals — it describes how typical brain weight varies across species, not how an individual animal’s brain weight relates to its own body weight. Second, the two species with the largest residuals in our final model, Man and the water opossum, aren’t random noise: humans and other primates are well known in the comparative-anatomy literature to sit above the general mammalian scaling line, while marsupials like the water opossum tend to sit below it. That pattern suggests our model is missing a systematic factor — something like taxonomic group (primate vs.&nbsp;non-primate, placental vs.&nbsp;marsupial) — that a multiple regression model could incorporate. Third, with only 30 species sampled from roughly 6,000 living mammal species, we should be cautious about how far these conclusions generalize, particularly to groups (like bats or cetaceans) that are thinly represented in this sample.</p>
<p>A natural follow-up question: does adding taxonomic group as a second predictor explain away the Man and water-opossum residuals, or is there still meaningful species-to-species variation in brain size left over even after accounting for both body size and broad taxonomic group?</p>
</section>
<section id="references" class="level1 page-columns page-full">
<h1>References</h1>
<p>Allison, T., &amp; Cicchetti, D. V. (1976). Sleep in mammals: Ecological and constitutional correlates. <em>Science, 194</em>(4266), 732–734.</p>
<p>Jerison, H. J. (1973). <em>Evolution of the brain and intelligence</em>. Academic Press. [<em>placeholder citation — for your own report, find and read a real peer-reviewed source and cite it properly</em>]</p>



<div class="no-row-height column-margin column-container"><div class="">
<p><strong>Why this works:</strong> the Allison &amp; Cicchetti citation is real — it’s the actual source of this dataset, so it belongs here regardless of which prompt you’re working from. The Jerison entry is a deliberate placeholder for the background-research citation the rubric requires; yours needs to be a source you actually read, not one I handed you.</p>
</div></div></section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aluby\.github\.io\/stat230\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>